import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Eglix - Application de Gestion d\'Église au Togo | LafiaTech',
  description: 'Eglix est la solution complète de gestion d\'église moderne au Togo. Gérez vos membres, finances, activités et rapports avec une interface intuitive. Développé par LafiaTech.',
  keywords: [
    'gestion église Togo',
    'application église',
    'Eglix',
    'gestion membres église',
    'gestion financière église',
    'logiciel église Togo',
    'système gestion église',
    'LafiaTech',
    'église numérique Togo',
    'gestion paroisse',
    'logiciel religieux',
    'application gestion église'
  ],
  authors: [{ name: 'LafiaTech' }],
  creator: 'LafiaTech',
  publisher: 'LafiaTech',
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  openGraph: {
    type: 'website',
    locale: 'fr_TG',
    url: 'https://lafiatech.com/eglix',
    siteName: 'LafiaTech',
    title: 'Eglix - Application de Gestion d\'Église au Togo',
    description: 'Solution complète de gestion d\'église moderne au Togo. Gérez membres, finances et activités avec Eglix.',
    images: [
      {
        url: '/eglix-landing.png',
        width: 1200,
        height: 630,
        alt: 'Eglix - Interface de gestion d\'église',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Eglix - Application de Gestion d\'Église au Togo',
    description: 'Solution complète de gestion d\'église moderne au Togo. Développé par LafiaTech.',
    images: ['/eglix-landing.png'],
  },
  alternates: {
    canonical: 'https://lafiatech.com/eglix',
  },
  category: 'technology',
  classification: 'Application de gestion d\'église',
  other: {
    'geo.region': 'TG',
    'geo.country': 'Togo',
    'geo.placename': 'Togo',
    'DC.title': 'Eglix - Application de Gestion d\'Église au Togo',
    'DC.creator': 'LafiaTech',
    'DC.subject': 'Gestion d\'église, Application web, Togo',
    'DC.description': 'Solution complète de gestion d\'église moderne au Togo',
    'DC.publisher': 'LafiaTech',
    'DC.contributor': 'LafiaTech',
    'DC.date': '2024',
    'DC.type': 'Software',
    'DC.format': 'text/html',
    'DC.identifier': 'https://lafiatech.com/eglix',
    'DC.source': 'https://lafiatech.com',
    'DC.language': 'fr',
    'DC.relation': 'https://lafiatech.com',
    'DC.coverage': 'Togo',
    'DC.rights': 'Copyright LafiaTech',
  },
}
